server:
  port: 8092    
spring:     #定义springmvc视图解析器
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp

#dubbo配置项
dubbo:
  scan:
    basePackages: com.jt  #指定包路径
  application:
    name: consumer-web   #业务标识 自己定义的
  registry:
    address: zookeeper://192.168.113.128:2181?backup=192.168.113.128:2182,192.168.113.128:2183



  